"bufferline"
   let g:bufferline_modified = '*'

" Strip trailing whitespace
function! StripWhitespace()
	let save_cursor = getpos(".")
	let old_query = getreg('/')
	:%s/\s\+$//e
	call setpos('.', save_cursor)
	call setreg('/', old_query)
endfunction

" grep
set grepformat=%f:%l:%c:%m,%f:%l:%m
